// <auto-generated />
using System;
using Imagist_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Imagist_Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107150749_UserEntityAddattribute")]
    partial class UserEntityAddattribute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Imagist_Library.Model.Album", b =>
                {
                    b.Property<long>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AlbumDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("OwingUserId")
                        .HasColumnType("bigint");

                    b.HasKey("AlbumId");

                    b.HasIndex("OwingUserId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Imagist_Library.Model.Photo", b =>
                {
                    b.Property<long>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AlbumId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("OwingUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailObjectId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PhotoId");

                    b.HasIndex("AlbumId");

                    b.HasIndex("OwingUserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Imagist_Library.Model.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("profileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Imagist_Library.Model.Album", b =>
                {
                    b.HasOne("Imagist_Library.Model.User", "OwingUser")
                        .WithMany("Albums")
                        .HasForeignKey("OwingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwingUser");
                });

            modelBuilder.Entity("Imagist_Library.Model.Photo", b =>
                {
                    b.HasOne("Imagist_Library.Model.Album", "Album")
                        .WithMany("Photos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imagist_Library.Model.User", "OwingUser")
                        .WithMany("Photos")
                        .HasForeignKey("OwingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Imagist_Library.Photo.PhotoMetaData", "MetaData", b1 =>
                        {
                            b1.Property<long>("PhotoId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Aperture")
                                .HasColumnType("longtext");

                            b1.Property<string>("FileExtensionName")
                                .HasColumnType("longtext");

                            b1.Property<string>("FileType")
                                .HasColumnType("longtext");

                            b1.Property<string>("FocalLength35")
                                .HasColumnType("longtext");

                            b1.Property<string>("ISO")
                                .HasColumnType("longtext");

                            b1.Property<int>("ImageHeight")
                                .HasColumnType("int");

                            b1.Property<int>("ImageWidth")
                                .HasColumnType("int");

                            b1.Property<string>("Lens")
                                .HasColumnType("longtext");

                            b1.Property<string>("MIMEType")
                                .HasColumnType("longtext");

                            b1.Property<string>("Make")
                                .HasColumnType("longtext");

                            b1.Property<string>("Model")
                                .HasColumnType("longtext");

                            b1.Property<DateTime?>("OriginalTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("ShutterSpeed")
                                .HasColumnType("longtext");

                            b1.HasKey("PhotoId");

                            b1.ToTable("Photos");

                            b1.WithOwner()
                                .HasForeignKey("PhotoId");
                        });

                    b.Navigation("Album");

                    b.Navigation("MetaData")
                        .IsRequired();

                    b.Navigation("OwingUser");
                });

            modelBuilder.Entity("Imagist_Library.Model.Album", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Imagist_Library.Model.User", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
